#!/bin/ksh
# Script de lancement des PNL generiques.
#-------------------------------------------------------------------
# Diverses initialisations de variables obligatoires
#-------------------------------------------------------------------
#-- Date passee en argument par CONTROLM
ODATE=${1}
[ "X${ODATE}" = "X" ] && echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Parm ODATE not found" && exit 1
#-- Closing
CLOSING=${2}
[ "X${CLOSING}" = "X" ] && echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Parm CLOSING not found" && exit 1
#-- JobName
JOB=${3}
[ "X${JOB}" = "X" ] && echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Parm JOB not found" && exit 1
#-- Chargement de l'environnement GEC
#-- exporte les variables CTM0, GEHLOG, GEDAA, GEDAACC et GEDSOFT
ctrlmExports ${0}
switch ${GEHLOG} 1>/dev/null
#-------------------------------------------------------------------
# Chargement des variables d'environnement
#-------------------------------------------------------------------
[ -f ${GEDAAETC}/env.ksh ] && . ${GEDAAETC}/env.ksh
[ -f ${GEDAACC}/etc/env.ksh ] && . ${GEDAACC}/etc/env.ksh
#-------------------------------------------------------------------
# Initialisation des variables n'ayant pas a etre modifiees
#-------------------------------------------------------------------
#-- Creation auto des repertoires necessaires.
#-- Repertoires logs/${JOB}
if [ ! -d ${GEDAACH}/logs/${JOB} ]; then
        mkdir -p  ${GEDAACH}/logs/${JOB}
fi
#-- Repertoires travaux/${JOB}
if [ ! -d ${GEDAACH}/travaux/${JOB} ]; then
        mkdir -p  ${GEDAACH}/travaux/${JOB}
fi
export SUMMITSPOOLDIR="${SUMMITSPOOLDIR}/$JOB"
export SUMMITERRDIR="${SUMMITERRDIR}/$JOB"
_CODE=0
#-------------------------------------------------------------------
# Initialisation des variables specifiques au job
#-------------------------------------------------------------------

case ${CLOSING} in
        PARIS)  _CVID="MO";;
        ASIE)   _CVID="MO15";;
        NY)     _CVID="MO21";;
        *)              echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - CLOSING non valable (Date disponible : PARIS,ASIE,NY)" && exit 1;;
esac

_BATCHDATE=`${SPEHOME}/sbin/recupBatchDate.ksh "CDCMPARIS"`
_CODE_RECUP=$?
if [ ${_CODE_RECUP} -ne 0 ]
  then
    echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - La recuperation de la date est en erreur."
    exit ${_CODE_RECUP}
fi

_EXE_NAME="cpcurves"
_EXE_PARM=" -TYPE CESPRADJ -IMPLYCESPRADJ -CVID ${_CVID} -X ${_BATCHDATE} -Y ${_BATCHDATE}"

#-------------------------------------------------------------------"
echo "DEBUT JOB ${CTM0} $(date "+%Y%m%d-%H%M%S") -------------------"
#-------------------------------------------------------------------"

echo "[INFO] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Demarrage de l'execution du job => ${_EXE_NAME}"
echo "[INFO] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Les parametres suivants => ${_EXE_PARM} seront utilises."
echo "[INFO] - [$(date "+%Y-%m-%d-%H-%M-%S")] - La base utilisee est => ${DSQUERY}:${SUMMITDBNAME}"

${_EXE_NAME} ${_EXE_PARM}
_CODE=$?

if [ ${_CODE} -ne 0 ]
  then
    if [ -f ${SUMMITERRDIR}/ERRORLOG.DAT ]
      then
        mv ${SUMMITERRDIR}/ERRORLOG.DAT  ${SUMMITERRDIR}/ERRORLOG.DAT.$(date "+%Y%m%d_%H%M%S")
    fi
    GecMail -o "[${GEIENV}][ERROR] ${JOB} en erreur le $(date "+%Y-%m-%d") à $(date "+%H-%M-%S")" -d "${MAIL_TO}" -m "Le Job ${JOB} est en erreur, merci de regarder."
    echo "[ERROR] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Code retour = ${_CODE}"
    echo "FIN JOB ${CTM0} $(date "+%Y%m%d-%H%M%S")"
    exit ${_CODE}
  else
    if [ -f ${SUMMITERRDIR}/ERRORLOG.DAT ]
      then
        mv ${SUMMITERRDIR}/ERRORLOG.DAT  ${SUMMITERRDIR}/ERRORLOG.DAT.$(date "+%Y%m%d_%H%M%S")
    fi
    echo "[INFO] - [$(date "+%Y-%m-%d-%H-%M-%S")] - Code retour = ${_CODE}"
fi

echo "FIN JOB ${CTM0} $(date "+%Y%m%d-%H%M%S")"
exit ${_CODE}
